version: '3.8'

services:
  fhir_node1:
    image: ghcr.io/samply/blaze:latest
    container_name: fhir-node
    volumes:
      - synthea-output-data:/output
    networks:
      - blaze_network
    expose:
      - "8080"
    environment:
      - BLAZECTL_SERVER=${BLAZECTL_SERVER}
      - BLAZECTL_USER=${BLAZECTL_USER}
      - BLAZECTL_PASSWORD=${BLAZECTL_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./env/auth/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - fhir_node1
    networks:
      - blaze_network

networks:
  blaze_network:
    driver: bridge

volumes:
  synthea-output-data: